### ISSUE TITLE
Cleaning for Amazon .es, .pl, .ca, .eg, etc.

### ISSUE THREAD

**Issue by migcm** [DrKain/tidy-url#10]
**Website you would like added. Include multiple URLs if needed**

- https://www.amazon.es/Lacoste-Anal%C3%B3gico-Hombre-Cuarzo-2011016/dp/B07ND9N75K/?_encoding=UTF8&pd_rd_w=WtRtx&pf_rd_p=79b177d9-dec3-4902-8a80-f2ea2453e768&pf_rd_r=MDD53XXF52Q1F8PNPC3K&pd_rd_r=be654e33-0438-4811-930e-79191be4bab7&pd_rd_wg=tX5gT&ref_=pd_gw_unk&tag=atrapazon-21
- https://www.amazon.es/dp/B09LTTDGB1?tag=atrapazon-21
- https://www.amazon.es/Tommy-Hilfiger-Anal%C3%B3gico-Inoxidable-01791788/dp/B08H2F1VQJ/?_encoding=UTF8&pd_rd_w=lJLZK&pf_rd_p=79b177d9-dec3-4902-8a80-f2ea2453e768&pf_rd_r=SH8XSZ5V2X4MAP73W2MG&pd_rd_r=1f6a8a78-cbfd-4310-a6e9-d4db9d98f7ad&pd_rd_wg=J4idt&ref_=pd_gw_unk

**Additional context**
The problem is the domain extension. Amazon extension domains than ".com" (eg: .es, .pl, .ca, .eg, etc.) are not being considered.

The full list of Amazon domains is on Wikipedia: https://en.wikipedia.org/wiki/Amazon_(company)

**Comment by DrKain** [comment]
Thank you for reporting, the amazon regex has been updated and should now match all the domains you listed
