### ISSUE TITLE
Broken: google.com

### ISSUE THREAD

**Issue by nickm980** [DrKain/tidy-url#110]
**URL before cleaning:**

-   https://www.google.com/search?q=test&rlz=1C1JSBI_enUS1072US1073&oq=test&gs_lcrp=EgZjaHJvbWUqDAgAEEUYOxixAxiABDIMCAAQRRg7GLEDGIAEMgoIARAAGLEDGIAEMgcIAhAAGIAEMgcIAxAAGIAEMgoIBBAAGLEDGIAEMgYIBRBFGEEyBggGEEUYPDIGCAcQRRg80gEHNTU0ajBqN6gCALACAA&sourceid=chrome&ie=UTF-8

**Current result when cleaning:**

-   https://www.google.com/search?q=test&gs_lcrp=EgZjaHJvbWUqDAgAEEUYOxixAxiABDIMCAAQRRg7GLEDGIAEMgoIARAAGLEDGIAEMgcIAhAAGIAEMgcIAxAAGIAEMgoIBBAAGLEDGIAEMgYIBRBFGEEyBggGEEUYPDIGCAcQRRg80gEHNTU0ajBqN6gCALACAA&ie=UTF-8

**Expected outcome:**

-   https://www.google.com/search?q=test

**Extra Information:**

-   Browser or OS: Chrome
-   Version: 

**Additional context**
`
import { TidyURL } from "tidy-url";

const url = TidyURL.clean(
  "https://www.google.com/search?q=test&rlz=1C1JSBI_enUS1072US1073&oq=test&gs_lcrp=EgZjaHJvbWUqDAgAEEUYOxixAxiABDIMCAAQRRg7GLEDGIAEMgoIARAAGLEDGIAEMgcIAhAAGIAEMgcIAxAAGIAEMgoIBBAAGLEDGIAEMgYIBRBFGEEyBggGEEUYPDIGCAcQRRg80gEHNTU0ajBqN6gCALACAA&sourceid=chrome&ie=UTF-8"
);
console.log(url.url);
`

The examples from the README for google.com are working but not when I paste in this link

**Comment by DrKain** [comment]
Thank you for reporting, I'll push an update shortly adding `gs_lcrp`. I'll not be removing `ie` as this can be useful in some cases.
