### ISSUE TITLE
Website: vi-control.net

### ISSUE THREAD

**Issue by HiEnergy** [DrKain/tidy-url#111]
**Example URLs:**

```
https://vi-control.net/community/
```

**Bad params:**

- source

**Additional context:**  
Any posts in the forum on vi-control.net that contain links to external web pages will have a parameter "source=<URL>" added to them.
So if I create a forum post linking to "https://google.com" or "http://example.com/?foo=bar", these links will be transformed to "https://google.com?source=https://vi-control.net/community/" and "http://example.com/?foo=bar&source=https://vi-control.net/community/"

**Comment by DrKain** [comment]
Would you mind linking a thread that contains an external link so I can look further into this please?

**Comment by DrKain** [comment]
I had a look around, found these:  

```
https://www.youtube.com/watch?v=dQw4w9WgXcQ&source=https://vi-control.net/community
https://pxc-coding.com/de/portfolio/donotspy10/?source=https://vi-control.net/community
https://www.native-instruments.com/en/support/knowledge-base/show/3671/windows-78-tuning-tips-for-audio-processing/?source=https://vi-control.net/community
```

This is a tricky case because all rules are matched by the host but these cover a bunch of different domains without being able to tell where they came from. In the browser script it's easy enough but not anywhere else, so I need some time to think this over. Thank you for reporting.

**Comment by HiEnergy** [comment]
Thank you for developing this helpful tool.

Perhaps the rule can be generalized further. If a website `$WEBSITE` has a link in a "pseudo-regex" form of `http(s?)://$SOME_URL?source=$WEBSITE` or `http(s?)://$SOME_URL?$SOME_PARAMETERS&source=$WEBSITE`, then drop the `[&?]source=$WEBSITE` part.

**Comment by DrKain** [comment]
As per your recommendation I added the following rule:

```js
{
    name: 'vi-control.net',
    match: /[&?]source=https:\/\/vi-control\.net(?:\/community|$)/gi,
    match_href: true,
    rules: ['source']
}
```

I may modify it to only use the community path later on, as I haven't seen any other ones used. Thank you for opening the issue and I hope this suits you.
