### ISSUE TITLE
Website: Ebay.es /.com / .co.uk

### ISSUE THREAD

**Issue by migcm** [DrKain/tidy-url#12]
**Ebay**

- https://www.ebay.es/itm/353897353157?_trkparms=amclksrc%3DITM%26aid%3D1110006%26algo%3DHOMESPLICE.SIM%26ao%3D1%26asc%3D20200818143230%26meid%3Dead83d8ce8fa4ba9bf5b80844b50b982%26pid%3D101224%26rk%3D1%26rkt%3D5%26sd%3D353870038414%26itm%3D353897353157%26pmt%3D1%26noa%3D1%26pg%3D2047675%26algv%3DDefaultOrganicWeb%26brand%3DXiaomi&_trksid=p2047675.c101224.m-1
- https://www.ebay.es/itm/Cinta-de-correr-plegable-electrica-FITFIU-1500w-14km-h-pantalla-LCD-y-pulsometro-/313633090831?ff3=4&pub=5575101662&toolid=10001&campid=5338578859&customid=&mkevt=1&mkcid=1&mkrid=1185-53479-19255-0&ufes_redirect=true
- https://www.ebay.es/itm/284730185104?hash=item424b3dd590%3Ag%3AirkAAOSwR99iRUcK&_trkparms=%2526rpp_cid%253D6225cd6e2720d84f87ae14ae&amdata=enc%3AAQAGAAAAkHPkBsjenI5ivTxJ%2Bjs5T8H7gFOKifgoyPoYDeASMpi4HMr0LVa36ckt%2F7hZwO%2FSRLmi62NcgE1cP4t%2Bx5hwpkP9bOgH4aX1KRw%2BhdE%2BL1Oin7iFoJ5D0WZ6IKTG3AHGYp927YHhfLKqGEcxxDQiAHb8hTmyQRYjjGIYhJ34KdSFQ4QbdwpGs8wfLd4OnY7bWg%3D%3D&mkcid=1&mkrid=1185-53479-19255-0&siteid=186&campid=5338485638&toolid=20013&mkevt=1
- https://www.ebay.es/itm/224806798415?hash=item345787844f%3Ag%3AGkkAAOSwtO1iRUyH&_trkparms=%2526rpp_cid%253D6225cd6e2720d84f87ae14ae&var=523698538100&amdata=enc%3AAQAGAAAAkPgcq1ob9n8MNx6hpcpgJ%2FKLDEQRIDRaxa4RrABCX9rkPhbYC%2FjUPvF5IEfbW3TDQ6%2FH%2BaBwyZTLGjgIg6rBls6b170r%2Be6iXGOIxAufQDEvg8hITlBIaG3oBk9wiXXQ4qYU%2FSBe8ccBHAaSABzIiqiK7ufJuhkeQo%2FztD6%2BK8gvRZxlEKg%2FRFcdbAiMFfa8Hw%3D%3D&mkcid=1&mkrid=1185-53479-19255-0&siteid=186&campid=5338467301&customid=&toolid=20012&mkevt=1
- https://www.ebay.es/itm/373960634437?ff3=4&pub=5575101662&toolid=10001&campid=5338578859&customid=&mkevt=1&mkcid=1&mkrid=1185-53479-19255-0&ufes_redirect=true
- https://pages.ebay.es/cupon/2022/DECORA22/index.html?mkcid=1&mkrid=1185-53479-19255-0&siteid=186&campid=5338628502&customid=&toolid=10001&mkevt=1
- https://www.ebay.es/itm/284730185104?mkevt=1&mkcid=1&mkrid=1185-53479-19255-0&campid=5338467301&toolid=20012

**Bad parameters.**

- amdata
- var
- hash
- _trkparms
- campid
- customid
- ff3
- pub
- toolid
- mkevt
- mkcid
- mkrid
- ufes_redirect
- siteid
- _trksid

**Additional context**
-

**Comment by DrKain** [comment]
I've tested each of these best I can but if something breaks please let me know. There's very little documentation of the url parameters ebay uses so most of it trial and error

**Comment by migcm** [comment]
Yes, of course. Thanks!
