### ISSUE TITLE
Website: shopee.com /.es / etc.

### ISSUE THREAD

**Issue by migcm** [DrKain/tidy-url#13]
**Website you would like added. Include multiple URLs if needed**

- https://shopee.es/Pulsera-De-Im%C3%A1n-Caliente-2021-Hecho-A-Mano-Ajustable-Cuerda-Juego-Braslet-Infinito-Amor-Par-Braclet-Brazalete-Rojo-De-La-Suerte-Regalo-i.538623460.8094382868?utm_source=an_22220520000&utm_medium=affiliates&utm_campaign=0hag3wq44j-&utm_content=713856-85e389d75f117ecf759c7561fcd8aecf---&af_siteid=an_22220520000&pid=affiliates&af_click_lookback=7d&af_viewthrough_lookback=1d&is_retargeting=true&af_reengagement_window=7d&af_sub_siteid=713856-85e389d75f117ecf759c7561fcd8aecf---&c=0hag3wq44j-
- https://shopee.es/-1-Pieza-Profesional-80-100-150-180-240-Grano-De-Doble-Cara-Pulido-De-La-Mitad-Luna-Lima-De-U%C3%B1as-DIY-Arte-Herramientas--i.567456457.14319235824?utm_source=an_22220520000&utm_medium=affiliates&utm_campaign=0hag3wq44j-&utm_content=583003-b3ee8ca58ad1d622a532ae08a5f4eaff---&af_siteid=an_22220520000&pid=affiliates&af_click_lookback=7d&af_viewthrough_lookback=1d&is_retargeting=true&af_reengagement_window=7d&af_sub_siteid=583003-b3ee8ca58ad1d622a532ae08a5f4eaff---&c=0hag3wq44j-
- https://shopee.es/Tap%C3%B3n-De-Boca-De-Aceite-De-Oliva-Vino-Tinto-A-Prueba-De-Polvo-2-Piezas-Boquilla-i.569147984.12741241980?utm_source=an_22220520000&utm_medium=affiliates&utm_campaign=0hag3wq44j-&utm_content=583003-d4e5229598d31e1281f14414b6b1802b---&af_siteid=an_22220520000&pid=affiliates&af_click_lookback=7d&af_viewthrough_lookback=1d&is_retargeting=true&af_reengagement_window=7d&af_sub_siteid=583003-d4e5229598d31e1281f14414b6b1802b---&c=0hag3wq44j-
- https://shopee.es/Mini-sellador-t%C3%A9rmico-de-bolsas-utensilio-de-cocina-port%C3%A1til-para-cierre-de-bolsas-de-comida-para-uso-dom%C3%A9stico%EF%BC%8CCazador-de-focas-i.607155560.14311155529?utm_source=an_22220520000&utm_medium=affiliates&utm_campaign=0hag3wq44j-&utm_content=583003-00a77f1feb3df881a781e516e538c6de---&af_siteid=an_22220520000&pid=affiliates&af_click_lookback=7d&af_viewthrough_lookback=1d&is_retargeting=true&af_reengagement_window=7d&af_sub_siteid=583003-00a77f1feb3df881a781e516e538c6de---&c=0hag3wq44j-
- https://shopee.es/?utm_medium=cpc&utm_source=planning_chollometro&utm_campaign=track_organicpost

**Bad parameters.**

- utm_source
- utm_medium
- utm_campaign
- utm_content
- af_siteid
- pid
- af_click_lookback
- af_viewthrough_lookback
- is_retargeting
- af_reengagement_window
- af_sub_siteid
- c

**Additional context**
-

**Comment by DrKain** [comment]
> utm_source
utm_medium
utm_campaign
utm_content

These should be handled by the global rules already. I'll add the others shortly

**Comment by migcm** [comment]
Great! Thanks, @DrKain.

Congrats for the project!
