### ISSUE TITLE
Website: inyourarea.co.uk

### ISSUE THREAD

**Issue by DrKain** [DrKain/tidy-url#38]
**Website you would like added. Include multiple URLs if needed**

```
https://www.inyourarea.co.uk/?branding=getwestlondon&from_reach_primary_nav=getwestlondon
https://www.inyourarea.co.uk/localservices?branding=getwestlondon
https://www.inyourarea.co.uk/?branding=getwestlondon&from_reach_footer_nav=getwestlondon
```

**Bad parameters. Leave blank if you don't know.**

- from_reach_primary_nav
- from_reach_footer_nav
- branding

**Additional context**

**Comment by akshay-patade** [comment]
HI DrKain,

Could you please elaborate more about this issue?

**Comment by DrKain** [comment]
@akshay-patade The purpose of this package is to strip tracking or 'garbage' parameters from URLs around the web that don't directly impact the functionality of the page. 
This issue is to add support for the domain `inyourarea.co.uk`
