### ISSUE TITLE
Update: fiverr.com

### ISSUE THREAD

**Issue by DrKain** [DrKain/tidy-url#39]
**Example URLs:**

```
https://www.fiverr.com/misty_mole?referrer_gig_slug=do-a-modern-minimalist-logo-design&ref_ctx_id=494a863f3c0594a88add19f396d182a9&imp_id=5fbdc879-2f6b-4b32-9fbb-d773b1221a42
https://www.fiverr.com/ingeniousarts/design-unique-and-modern-minimalist-logo?context_referrer=subcategory_listing&ref_ctx_id=494a863f3c0594a88add19f396d182a9&pckg_id=1&pos=28&context_type=rating&funnel=494a863f3c0594a88add19f396d182a9&seller_online=true&imp_id=74176086-9071-4dcc-83e5-e4a818b2d9b6
https://www.fiverr.com/shiv_graphix/design-2-outstanding-logo-in-24-hours?context_referrer=subcategory_listing&ref_ctx_id=494a863f3c0594a88add19f396d182a9&pckg_id=1&pos=29&context_type=rating&funnel=494a863f3c0594a88add19f396d182a9&seller_online=true&imp_id=95a1c0d8-21ad-443f-a937-09e92016cd3c
```

**Bad params:**

- context_referrer
- referrer_gig_slug
- ref_ctx_id
- funnel
- imp_id
   
These are untested and should be verified before use. The first two should be safe to remove, but the last 3 need to be tested to ensure the page doesn't break or change based on the value.   
An entry already exists for fiverr.com, so if someone else takes care of this issue please update the existing entry instead of adding a new one.

**Comment by elonyavist** [comment]
Hi @DrKain, I'd like to take care of it if you agree.

**Comment by DrKain** [comment]
Sure thing @elonyavist

**Comment by elonyavist** [comment]
Hi @DrKain, I see also these params:
```
'pckg_id' => '1',
'pos' => '28',
'context_type' => 'rating',
'seller_online' => 'true'
```
shall we try to eliminate them to see if it works as well?

**Comment by DrKain** [comment]
From the names alone they don't seem to be "bad" parameters that fit the conditions for this package.  

Any parameter added to the rules file needs to be tested to ensure it does not break functionality on the website it's applied to. The easiest way to do this is to load the page with each param removed to compare to the original URL, you can usually see visual differences from valid parameters while "bad" parameters only affect back-end logging and such.  

If you're unsure about the point of this package, it's to remove tracking or "junk" parameters from URLs, a good example of these are [UTM Parameters](https://en.wikipedia.org/wiki/UTM_parameters) that have no functionality on the page itself.
