### ISSUE TITLE
Need rebrand or include new keywords for S,E,O

### ISSUE THREAD

**Issue by gotshadowbantempaccount** [DrKain/tidy-url#6]
This is what i looking for thx but

when try to google it: **nodejs tracking url github** it show nothing maybe you should add more keywords on home page  that include keywords like nodejs tracking, clean url, url tracking remove

Show me only some old crap when looking for this
https://github.com/newhouse/url-tracking-stripper

**Comment by DrKain** [comment]
Thank you for the tips but this isn't a priority for me. There are other packages and tools out there that do the same thing, a lot of them better such as the [ClearURLs](https://addons.mozilla.org/en-US/firefox/addon/clearurls/) extension.   
  
I've expanded the global rules with several from the link you provided but I see no reason to rebrand or modify the keywords
