### ISSUE TITLE
Website: boxofficemojo.com

### ISSUE THREAD

**Issue by DrKain** [DrKain/tidy-url#68]
**Example URLs:**

```
https://boxofficemojo.com/year/2023/?ref_=bo_lnav_hm_shrt
https://www.boxofficemojo.com/weekend/?ref_=bo_nb_hm_secondarytab
https://www.boxofficemojo.com/calendar/2023-11-17/?ref_=bo_hm_RELEASE_DATE_CHANGES_WIDGET_5
```

**Bad params:**

- ref_

**Additional context:**  
Add any other information about the website here that might be useful to know.

**Comment by camilaezama** [comment]
Hello! I would like to work on this issue, could you assign it to me?
