### ISSUE TITLE
Website: aliexpress.com

### ISSUE THREAD

**Issue by rendomnet** [DrKain/tidy-url#7]
**Website you would like added. Include multiple URLs if needed**

- https://aliexpress.com/item/1005003170671440.html?blablablal
- https://aliexpress.com/item/1005003170671440.html

**Bad parameters. Leave blank if you don't know.**

**Additional context**

It also have regional versions like aliexpress.*/

**Comment by DrKain** [comment]
Both the links you provided seem to be fine. What parameters are you having trouble with? There's roughly 20 rules for aliexpress already

**Comment by rendomnet** [comment]
@DrKain https://aliexpress.ru/item/1005003170671440.html?gatewayAdapt=glo2rus&spm=a2g2w.home.15002.76.5a50501dwThjGw&_evo_buckets=165609,165598,188873,224373,176818,194275&sku_id=12000024476377327&gps-id=pcJustForYou&scm=1007.13562.265877.0&scm_id=1007.13562.265877.0&scm-url=1007.13562.265877.0&pvid=ed2b99b7-359e-4c84-8a13-761e16c1d360&_t=gps-id:pcJustForYou,scm-url:1007.13562.265877.0,pvid:ed2b99b7-359e-4c84-8a13-761e16c1d360,tpp_buckets:21387%230%23250274%230#/

**Comment by DrKain** [comment]
Ah, I was not aware aliexpress used anything other than `.com`, Thank you for reporting. I'll update in a moment

**Comment by rendomnet** [comment]
@DrKain Thank you! Great module
