### ISSUE TITLE
Broken: amazon tracking links

### ISSUE THREAD

**Issue by LeGrosSancho** [DrKain/tidy-url#88]
**URL before cleaning:**

-   https://m7267kld.r.us-west-2.awstrack.me/L0/https:%2F%2Fauth.pathapplication.com%2Fprovider%2Fchange-password/1/SOME_RANDOM_ID_1/SOME_RANDOM_ID_2

**Current result when cleaning:**

-   https://auth.pathapplication.com/provider/change-password/1/SOME_RADOM_ID_1/SOME_RANDOM_ID_2

**Expected outcome:**

-   https://auth.pathapplication.com/provider/change-password

**Extra Information:**

**Additional context**
By the way I also noticed that the result we get from `TidyURL.clean()` has an empty "removed" array, is it expected?
Here is a screenshot of the info object:
<img width="838" alt="Screenshot 2023-07-28 at 13 46 17" src="https://github.com/DrKain/tidy-url/assets/33290778/df1f37b2-fabd-4850-bed1-7e3d660a7c54">

**Comment by DrKain** [comment]
Thanks for reporting, I'll look into this shortly.
The `removed` array would contain a list of parameters that have been removed, but in this case the issue is with the amp rule

**Comment by LeGrosSancho** [comment]
Oh okay I see thanks a lot! 
So if I need to check whether the link has changed or not, do you suggest to check `difference` or `reduction` (or something else)?

**Comment by DrKain** [comment]
If I remember right: `reduction` is the number of characters removed and `difference` is a percentage, they were originally meant for debugging.  
The best way to check if the link has changed: `data.url !== data.info.original`

**Comment by LeGrosSancho** [comment]
Okay I see, I will do it that way then, thanks a lot once again 🙏

**Comment by DrKain** [comment]
The updated rule should now return the correct URL, please let me know if you have any more issues with it

**Comment by DrKain** [comment]
I might be missing something here, but didn't the old return the expected outcome?

```
Input: https://m7267kld.r.us-west-2.awstrack.me/L0/https:%2F%2Fauth.pathapplication.com%2Fprovider%2Fchange-password/1/SOME_RANDOM_ID_1/SOME_RANDOM_ID_2
Clean: https://auth.pathapplication.com/provider/change-password/1/SOME_RANDOM_ID_1/SOME_RANDOM_ID_2
New Host: true
35.86% smaller (52 characters)
```

**Comment by LeGrosSancho** [comment]
Thanks for the revert. 🙏
Indeed looks like the link was cleaned correctly on your side, I think it's a misunderstanding with the report we received which wasn't clear... I will ask for some more details

Sorry for the inconvenience, but thanks a lot for your reactiveness.

**Comment by DrKain** [comment]
Hi @LeGrosSancho, any update on this? Is it safe to close?

**Comment by DrKain** [comment]
I'm going to give this 3 more days before closing. As far as I can see there is no issue with this package, so I'll wait a few more days before closing. If you or someone else wants to chime in here I'm more than happy to look into it, but with the lack of information there's really not much I can do here.

**Comment by LeGrosSancho** [comment]
Hey sorry I completely missed the notifications 😬 
Indeed, we did not received any updates on this report on our side, so I think we can close it completely.
Thanks, and again sorry for the inconvenience 😕
