### ISSUE TITLE
Bug: No utm tracker cleaned when allow_amp rule is set to true

### ISSUE THREAD

**Issue by LeGrosSancho** [DrKain/tidy-url#96]
Hello, I noticed that when setting `allow_amp` to true and cleaning a link containing utm trackers, the resulting link is not cleaned anymore.
Is it expected ? 🤔 

Example:
Cleaning `https://ads.com?utm_source=something` will give
- `https://ads.com?utm_source=something` when `allow_amp` is true
- `https://ads.com` when `allow_amp` is false

From what I've seen it was working in `1.7.3`, but not in `1.7.6`, I did not found time to investigate much, but I guess [this commit](https://github.com/ProtonMail/tidy-url/commit/272a0bcada498ee42265b658f01c6382bd32a3c2) changed the behaviour somehow.

If needed, I created a really dumb stackblitz running an app cleaning a simple link with `allow_amp` to true and false to show the difference (function is in `App.tsx`). If you change the version of tidy-url from `1.7.6` to `1.7.3`, you should see the difference.
Here is the [link](https://stackblitz.com/edit/stackblitz-starters-ddzqqp?file=package.json). I have some troubles to open it from Chrome not sure why, but it looks ok from Firefox in case you're also having troubles.

**Comment by DrKain** [comment]
As of the latest version (1.8.1) and the version you mentioned (1.7.3), the sample URL you provided should work as expected both locally and on the stackblitz you linked. 

![image](https://github.com/DrKain/tidy-url/assets/5300315/d681b77e-c9c7-49e2-a584-4ff843ab67d7)


The only instances when a URL is not modified is if it matches something in the `exclude` array, that might be what's happening in your case. There's only two rules using this, `facebook.com` and `cnn.com`

**Comment by LeGrosSancho** [comment]
Hmm sorry, I'm not sure to understand what you mean 😅 

With my sample URL, in `1.7.3`, after a clean, utm parameters are removed:
<img width="905" alt="Screenshot 2023-10-09 at 18 04 29" src="https://github.com/DrKain/tidy-url/assets/33290778/a80b9fca-46e3-4045-af60-8a4f54d278d4">

But in `1.7.6`, it's not the case anymore (same with `1.8.1`):
<img width="998" alt="Screenshot 2023-10-09 at 18 04 43" src="https://github.com/DrKain/tidy-url/assets/33290778/36715398-c979-4b6b-b354-a35d1930dd94">

I'm not using any `facebook` or `cnn.com` urls, so maybe this behaviour is expected, but I don't understand why there is a difference between these versions 🤔

**Comment by DrKain** [comment]
I'm not sure either, I'll have to leave this open until I can reliably reproduce the issue or at least find out what's causing this discrepancy.  
Thank you for reporting

**Comment by LeGrosSancho** [comment]
Sure, thanks 🙏

**Comment by DrKain** [comment]
Hi @LeGrosSancho, sorry for the long wait. I've just pushed a new version that should fix this issue. Sorry for the slow update, I've been a bit unwell and have not had the time to look into this further. Please let me know if you have any other problems

**Comment by LeGrosSancho** [comment]
Hey no worries, I hope you're feeling better now.
Thanks a lot for having a look 🙏 I will let you know if I have any other issue :)
